#define 		SPACE				1
#define			NEW_LINE			2
#define			KW_AND				3
#define			KW_OR				4
#define			KW_NOT				5
#define			KW_EQUAL			6
#define			KW_LESS				7
#define			KW_NIL				8
#define			KW_LIST				9
#define			KW_APPEND			10
#define			KW_CONCAT			11
#define			KW_SET				12		
#define			KW_DEFFUN			13
#define			KW_FOR				14
#define			KW_IF				15
#define			KW_EXIT				16
#define			KW_LOAD				17
#define			KW_DISP				18
#define			KW_TRUE				19
#define			KW_FALSE			20
#define			OP_PLUS				21
#define			OP_MINUS			22
#define			OP_DIV				23
#define			OP_MULT 			24
#define			OP_OP				25
#define			OP_CP				26
#define			OP_DBLMULT			27
#define			OP_OC 				28
#define			OP_CC 				29	
#define			OP_COMMA			30
#define			COMMENT				31
#define			VALUE				32
#define			IDENTIFIER			33
#define			SYNTAX_ERROR		34	
#define 		EOF_RETURN			0
